### ISSUE TITLE
安装遇到问题，请求帮助

### ISSUE THREAD

**Issue by jia95812** [shariqfarooq123/LooseControl#18]
(loosecontrol) E:\LooseControl-main>gradio app.py
Watching: 'E:\LooseControl-main' 'E:\LooseControl-main'

Loading pipeline components...:  67%|██████████████████████████████████▋                 | 4/6 [00:01<00:00,  3.35it/s]D:\ProgramData\anaconda3\envs\loosecontrol\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:01<00:00,  4.84it/s]
Traceback (most recent call last):
  File "E:\LooseControl-main\app.py", line 20, in <module>
    cn_with_cf.set_cf_attention()
  File "E:\LooseControl-main\loosecontrol.py", line 120, in set_cf_attention
    set_attn_processor(upblocks, CrossFrameAttnProcessor(), _remove_lora=_remove_lora)
  File "E:\LooseControl-main\loosecontrol.py", line 47, in set_attn_processor
    fn_recursive_attn_processor(name, module, processor)
  File "E:\LooseControl-main\loosecontrol.py", line 44, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "E:\LooseControl-main\loosecontrol.py", line 44, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  File "E:\LooseControl-main\loosecontrol.py", line 44, in fn_recursive_attn_processor
    fn_recursive_attn_processor(f"{name}.{sub_name}", child, processor)
  [Previous line repeated 1 more time]
  File "E:\LooseControl-main\loosecontrol.py", line 39, in fn_recursive_attn_processor
    module.set_processor(processor, _remove_lora=_remove_lora)
TypeError: Attention.set_processor() got an unexpected keyword argument '_remove_lora'

不确定是否是依赖环境的版本问题，我的环境是这样的：
(loosecontrol) E:\LooseControl-main>conda list
# packages in environment at D:\ProgramData\anaconda3\envs\loosecontrol:
#
# Name                    Version                   Build  Channel
accelerate                0.33.0                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.7.2             haa95532_0
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
diffusers                 0.30.0                   pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
fastapi                   0.112.0                  pypi_0    pypi
ffmpy                     0.4.0                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fsspec                    2024.2.0                 pypi_0    pypi
gradio                    4.41.0                   pypi_0    pypi
gradio-client             1.3.0                    pypi_0    pypi
gradio-editor3d           0.0.3                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.24.5                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
importlib-metadata        8.2.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_1
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.1.post1              pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
numpy                     1.26.3                   pypi_0    pypi
openssl                   3.0.14               h827c3e9_0
orjson                    3.10.7                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
peft                      0.12.0                   pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       24.0            py310haa95532_0
psutil                    6.0.0                    pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.10.14              he1021f5_1
python-dateutil           2.9.0.post0              pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
regex                     2024.7.24                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
ruff                      0.5.7                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                72.1.0          py310haa95532_0
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
starlette                 0.37.2                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tk                        8.6.14               h0416ee5_0
tokenizers                0.19.1                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
torch                     2.2.2+cu121              pypi_0    pypi
torchvision               0.17.2+cu121             pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
transformers              4.44.0                   pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
uvicorn                   0.30.5                   pypi_0    pypi
vc                        14.40                h2eaa2aa_0
vs2015_runtime            14.40.33807          h98bb1dd_0
websockets                12.0                     pypi_0    pypi
wheel                     0.43.0          py310haa95532_0
xz                        5.4.6                h8cc25b3_1
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_1

**Comment by luo0207** [comment]
@jia95812 Hi, it seems the question is caused by diffusers package. If you use older diffusers like 0.20.0, it will report the error like 
![image](https://github.com/user-attachments/assets/00fde13c-d80e-4deb-9b49-41afaee7abe6), while you use newer one like 0.26.0, the error will be same with yours. Try to `pip install diffusers=0.25.0`.
