### ISSUE TITLE
Exception: None ("LayerNormKernelImpl" not implemented for 'Half')

### ISSUE THREAD

**Issue by AGuyCoding** [shariqfarooq123/LooseControl#8]
after spending 2 hours installing all requirements i finally could run the demo.
when i enter in the promt something like "Bedroom" and click render, i get this:

Traceback (most recent call last):
  File "c:\users\myname\appdata\local\programs\python\python38\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "c:\users\myname\appdata\local\programs\python\python38\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by bayhill** [comment]
Same here, would love to understand what is causing this!

**Comment by AGuyCoding** [comment]
@bayhill 
> Same here, would love to understand what is causing this!

I think it has to do with our graphics card...I am not fully into that, but it looks like this "dtype=torch.float16" is our "problem".
So inside the code remove all occurrences of it or replace it with "dtype=torch.float32".
[Link](https://stackoverflow.com/questions/75641074/i-run-stable-diffusion-its-wrong-runtimeerror-layernormkernelimpl-not-implem)

Hope it helps

**Comment by bayhill** [comment]
Yeah, exactly what I found as well. Removing the dtype=torch.float16 from both app.py and loosecontrol.py helped and now it at least the "Render" button doesn't result in the above error, but it takes ages to process (on a Macbook Pro M2), I'm guessing because of CUDA incompatibility, but I am on very thin ice here 😄
